# Generated by Django 3.2.2 on 2021-05-10 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Roll_number', models.IntegerField(primary_key=True, serialize=False)),
                ('DOB', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.CharField(max_length=50)),
                ('roll_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.studentdetails')),
            ],
        ),
    ]
